import { Montserrat } from 'next/font/google'
import './globals.css'

const Font = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Sandang Gurau',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={Font.className}>{children}</body>
    </html>
  )
}
